---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(stringi)
library(colorspace)
library(ggplot2)
```

```{r}
file <- readLines("../R/colors.txt") %>% paste(collapse = "")

colors <- stri_match_all_regex(file, "rgb\\((\\d+), (\\d+), (\\d+)\\);")[[1]][,2:4] %>% 
  apply(2, as.numeric) %>% 
  apply(2, function(x) x / 256) %>%
  RGB %>% 
  as("LAB") %>%
  coords

distance <- function(a, b) {
  sum((a - b) ^ 2)
}

while (nrow(colors) > 44) {
  indexes <- seq(nrow(colors))
  mini <- rep(1000000, nrow(colors))
  sums <- numeric(nrow(colors))
  for (i in indexes) {
    for (j in indexes[-i]) {
      d <- distance(colors[i,], colors[j,])
      mini[i] <- min(mini[i], d)
      sums[i] <- sums[i] + d
    }
  }
  closest <- order(mini, sums)[1]
  colors <- colors[-closest,]
}

colors_hex <- colors %>% LAB %>% as("RGB") %>% hex

colors %>% LAB %>% as("RGB") %>% plot
```

```{r}
df <- data.frame(x = c(1:44), y = rep(1, 44), z = rep(colors_hex)

ggplot(df, aes(x, y, fill = z)) +
  geom_col() +
  scale_fill_manual(values = colors_hex)
```

