---
title: "R Notebook"
output: html_notebook
---
```{r}
library(stringi)
library(dplyr)

appendIfNotEmpty <- function(buffer, text, sep) {
  if(buffer == "")
    return(text)
  return(paste(buffer, text, sep=sep))
}
```

```{r}
parseScenario <- function(path) {
  options(stringsAsFactors = FALSE)
  con <- file(path, "r")
  name <- "!"
  chunk <- ""
  scene <- ""
  parsed <- data.frame(name=character(), dialog=character())
  
  while(TRUE) {
    line <-  readLines(con, n=1)
    if(length(line) == 0)
      break
    if(startsWith(line, "INT."))
      scene <- substring(line, 6)
    if(startsWith(line, "                          "))
      next
    if(startsWith(line, "                    ")) {
      newName <- stri_match_first_regex(line, "(\\p{L}+ *)*\\p{L}+")
      if(is.na(newName[1]) | startsWith(trimws(line), "("))
        next
      
      parsed <- rbind(parsed, data.frame(name=name, dialog=chunk, scene=scene))
      name <- newName[1]
      chunk <- ""
    } else if(startsWith(line, "          ")) {
      if(startsWith(trimws(line), "("))
        next
      chunk <- appendIfNotEmpty(chunk, trimws(line), " ")
    } else if(name == "!") {
      chunk <- appendIfNotEmpty(chunk, line, "\n")
    }else {
      parsed <- rbind(parsed, data.frame(name=name, dialog=chunk, scene=scene))
      chunk <- ""
      name <- "!"
    }
  }
  
  close(con)
  return(parsed)
}
```

```{r}
parseTime <- function(str) {
  t <- strsplit(gsub(",", ".", str), ":")[[1]]
  sum(as.numeric(t)*60^c(2, 1, 0))
}

parseSubtitles <- function(path) {
  options(stringsAsFactors = FALSE)
  con <- file(path, "r")
  parsed <- data.frame(text=character(), from=character(), to=character())
  
  while(TRUE) {
    if(length(readLines(con, n=1)) == 0)
      break
    line <- readLines(con, n=1)
    stTime <- parseTime(substring(line, 1, 13))
    endTime <- parseTime(substring(line, 19))
    text <- ""
    while(TRUE) {
      line <- readLines(con, n=1)
      if(line == "")
        break
      text <- appendIfNotEmpty(text, line, " ")
      if(startsWith(line, "-")) {
        parsed <- rbind(parsed, data.frame(text=text, from=stTime, to=endTime))
        text <- ""
      }
    }
    parsed <- rbind(parsed, data.frame(text=text, from=stTime, to=endTime))
  }
  
  close(con)
  return(parsed)
}
```

```{r}
toLetters <- function(str) {
  paste(stri_match_all_regex(str, "\\p{L}+")[[1]][,1], collapse="")
}
joinTime <- function(scenario, subtitles) {
  j <- 1
  from <- numeric(nrow(scenario))
  to <- numeric(nrow(scenario))
  matched <- character(nrow(scenario))
  for(i in 1:nrow(scenario)) {
    if(scenario$name[i] == "!")
      next
    j0 <- j
    curText <- subtitles$text[j]
    dial <- toLetters(scenario$dialog[i])
    while(nchar(toLetters(curText)) < 0.9*nchar(dial)) {
      j <- j+1
      curText <- paste(curText, subtitles$text[j])
    }
    
    if(adist(dial, toLetters(curText))[1] > 0.5*nchar(dial)) {
      j <- j0
      next
    }
    from[i] <- subtitles$from[j0]
    to[i] <- subtitles$to[j]
    matched[i] <- curText
    j <- j+1
  }
  cbind(scenario, start=from, end=to, subs=matched)
}
```

```{r}
scenario <- parseScenario("../data/LotR-1-sc.txt")
scenario$name[scenario$name == "FRODO DISAPPEARS"] <- "!"
subtitles <- parseSubtitles("../data/LotR-1-sub.srt")
data <- joinTime(scenario, subtitles)
data[data$subs == "" & data$name != "!", c("subs", "dialog")]
```

```{r}
i <- 1
freqs <- character()
heroes <- unique(data$name)[-1]
while(i <= nrow(data)) {
  curNames <- character()
  curScene <- data$scene[i]
  while(i <= nrow(data) & data$scene[i] == curScene) {
    if(data$name[i] != "!")
      curNames <- unique(c(curNames, data$name[i]))
    i <- i+1
  }
  for(j in curNames)
    for(k in curNames)
      freqs <- c(freqs, paste(j, k, sep="~"))
}
tbl <- table(freqs)

source <- character()
target <- character()
value <- integer()
for(i in 1:length(tbl)) {
  split <- strsplit(names(tbl)[i], "~")[[1]]
  source <- c(source, split[1])
  target <- c(target, split[2])
  value <- c(value, tbl[i])
}
links <- data.frame(source=source, target=target, value=value)
rownames(links) <- NULL

id <- character()
for(n in heroes) {
  id <- c(id, n)
}

jsonlite::write_json(list(nodes=id, links=links), "../interactions/data.json")
```

```{r}
data %>% filter(start != 0) %>%
  group_by(scene) %>% 
  summarise(max(end) - min(start))
```