---
title: "Untitled"
author: "Dawid Stelmach"
date: "25 października 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(httr)
library(jsonlite)
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(dplyr)
library(ggrepel)
library(tidyr)


token2 <- "35dbb2ebd27b23cfbec359dbd560adf2d4a5b27b"
tram <- data.frame(line = factor(c(1,2,3,4,6,7,9,10,11,13,14,15,17,18,20,22,23,24,25,26,27,28,31,33,35)))
bus <- data.frame(line = factor(c(102,103,104,105,107,108,109,110,111,112,114,115,116,117,118,119,120,121,
         122,123,124,125,126,127,128,129,131,132,133,134,135,136,138,139,140,141,
         142,143,145,146,147,148,149,151,152,153,154,155,156,157,158,159,160,161,
         162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,
         180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,
         198,199,201,202,203,204,205,206,207,208,209,211,212,213,214,217,218,219,
         221,222,225,227,240,245,256,262,300,303,304,305,306,311,314,317,318,320,
         323,326,331,332,334,338,340,345,365,379,397,401,402,409,411,412,414,500,
         501,502,503,504,507,509,511,512,514,516,517,518,519,520,521,522,523,525,
         527)))
machine <- rep("bus", length(bus$line))
bus <- cbind(bus, machine)
machine <- rep("tram", length(tram$line))
tram <- cbind(tram, machine)
lines <- rbind(tram, bus)

linie <- "10,17,33,514,520"
res <- GET(url = paste0("https://vavel.mini.pw.edu.pl/api/vehicles/v1/full/?line=", linie),
           add_headers(Authorization = paste("Token", token2)))
res <- content(res, as="text")
res <- jsonlite::fromJSON(as.character(res))

res_filtered <- res %>%
  filter(delayAtStop != "")

res_delayed <- res_filtered %>%
  filter(delay >= 120)

res_filtered <- res_filtered %>% 
  inner_join(lines)
```

```{r plot1, cache=TRUE, echo=FALSE}
qmplot(data = res_filtered, lon, lat)
```


```{r plot2, cache=TRUE, echo=FALSE}
qmplot(lon, lat, data = res_delayed, maptype = "toner-lite", color=line, size=delay)
```

```{r plot3, cache=TRUE, echo=FALSE}
ggplot(res_filtered, aes(x = line, y = delay, color = line)) +
  geom_boxplot(fill = "gray") +
  geom_jitter(position = position_jitter(width = 0.6)) +
  stat_summary(fun.y = mean, geom = "errorbar", aes(ymax = ..y.., ymin = ..y..), color = "purple", size = 1.5) +
  geom_rug(color = "black") +
  facet_wrap(~machine, ncol = 2, scales = "free")

```

