---
title: "Choinka"
author: Łukasz Ławniczak
output: html_notebook
---

```{r, echo=FALSE}
library(rbokeh)
rotate <- function(dir, alpha) {
    c(dir[1]*cos(alpha)-dir[2]*sin(alpha),
      dir[2]*cos(alpha)+dir[1]*sin(alpha))
}

needles <- function(y, len) {
  N <- as.integer(len*50)
  res <- matrix(nrow=2*N, ncol=4)
  for(i in 1:N) {
    p <- c((i-1)/50, y)
    alpha <- (i-1)/(N-1)*pi/8
    res[i,] <- c(p, p+rotate(c(0, -1), runif(1, alpha, 3*alpha)))
  }
  for(i in 1:N) {
    p <- c(-i/50, y)
    alpha <- -(i-1)/(N-1)*pi/8
    res[i+N,] <- c(p, p+rotate(c(0, -1), runif(1, 3*alpha, alpha)))
  }
  res <- as.data.frame(res)
  names(res) <- c("x1", "y1", "x2", "y2")
  res
}
```


```{r, include=FALSE}
p <- c(0, 7)
  top <- t(sapply(1:20, function(i) {
    c(p, p+rotate(c(0, -1), pi/4*(i-10)/10))
  }))
  colnames(top) <- c("x1", "y1", "x2", "y2")
  d1 <- rbind(
    needles(3, 2.5),
    needles(4, 1.8),
    needles(5, 1.1),
    needles(6, 0.5),
    top
  )

plt <- figure(xgrid=FALSE, ygrid=FALSE, xaxes=FALSE, yaxes=FALSE) %>%
  ly_segments(x0=x1, y0=y1, x1=x2, y1=y2, data=d1, color="#035b03") %>%
  ly_rect(xleft=-0.3, ybottom=1, xright=0.3, ytop=2, color="#472b01", fill_alpha=1)
```

```{r, echo=FALSE}
plt
```



